### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by StudentESE** [tuzz/hdl.js#1]
Hi,

I am thinking about to write my Phd paper about related stuff. Would you add the MIT and Apache 2 Licensing to your awesome work ?

Would be nice - I also would follow to use that licenses within a fork.
But it is important due to German law - without that I may not use it.

In every case thanks for your awesome work !!

**Comment by tuzz** [comment]
Hi,

I have now added the MIT License, I hope that's ok. I also made the default branch `gh-pages` which means you can view the sandbox [here](http://tuzz.github.io/hdl.js/examples/sandbox/).

Let me know if you have any questions.

I don't work on this project any more. Most of my effort recently has been on [Sentient](http://sentient-lang.org/), which uses some of the same ideas.

Thanks,
Chris

**Comment by StudentESE** [comment]
thanks 👍
